define: DUK_USE_DATE_NOW_WINDOWS
introduced: 1.0.0
default: false
tags:
  - date
  - portability
description: >
  Use Win32 API calls to get current datetime.  When enabled, appropriate
  date/time headers must be included.

# FIXME: add an include file metadata entry to cause default #include
# directives to be emitted?
